language: go
go:
  - master

before_install:
  - go mod download
  - cd $GOPATH/pkg/mod/gocv.io/x/gocv@v0.23.0
  - make install

install:
  - true

script:
  - cd $GOPATH/src/github.com/shanghuiyang/rpi-devices
  - go test -v ./...

notifications:
  slack: grab:OVbEkJH3R10nkyKfwT996cB5
